version: '3.9'

services:
  db:
    image: postgres:15
    container_name: heatmap_db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: heatmap_backend
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm run migrate && npm run dev"
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: heatmap_frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

volumes:
  pgdata:
